"""
DataPrep-DSL :: Backend Compilation & Execution (Module 3)
----------------------------------------------------------------
Two responsibilities, both driven off the SAME optimized IR so that
the generated script and the live preview can never disagree:

  1. codegen(ir)   -> a standalone, runnable Python (pandas) script
                       string -- this is the "compiled output" the
                       user can download and run independently of
                       this web app.
  2. execute(ir, dataframe_loader) -> runs the pipeline directly with
                       pandas for the live in-browser preview, and
                       returns per-step row/column counts (a
                       lightweight execution trace).
"""

import pandas as pd


class RuntimeExecError(Exception):
    def __init__(self, message, line):
        super().__init__(f"Runtime error at line {line}: {message}")
        self.line = line


# ---------------------------------------------------------------------
# 1. Code generation -> standalone python script
# ---------------------------------------------------------------------

def codegen(ir, csv_display_name="input.csv"):
    lines = [
        "# Auto-generated by DataPrep-DSL compiler -- Module 3 (Backend Compilation)",
        "# This script reproduces the pipeline exactly, without needing the DSL or web app.",
        "import pandas as pd",
        "",
    ]
    for instr in ir:
        df, a = instr.df, instr.args
        op = instr.op
        lines.append(f"# line {instr.line}: {op}")
        if op == "LOAD":
            lines.append(f'{df} = pd.read_csv("{csv_display_name}")')
        elif op == "DROP_COLUMNS":
            cols = a["columns"]
            lines.append(f"{df} = {df}.drop(columns={cols!r}, errors='ignore')")
        elif op == "FILLNA":
            col, strat = a["column"], a["strategy"]
            if strat == "MEAN":
                lines.append(f'{df}["{col}"] = {df}["{col}"].fillna({df}["{col}"].mean())')
            elif strat == "MEDIAN":
                lines.append(f'{df}["{col}"] = {df}["{col}"].fillna({df}["{col}"].median())')
            elif strat == "MODE":
                lines.append(f'{df}["{col}"] = {df}["{col}"].fillna({df}["{col}"].mode().iloc[0])')
            elif strat == "ZERO":
                lines.append(f'{df}["{col}"] = {df}["{col}"].fillna(0)')
            else:
                lines.append(f'{df}["{col}"] = {df}["{col}"].fillna({strat})')
        elif op == "NORMALIZE":
            col = a["column"]
            lines.append(f'_min, _max = {df}["{col}"].min(), {df}["{col}"].max()')
            lines.append(f'{df}["{col}"] = ({df}["{col}"] - _min) / (_max - _min) if _max != _min else 0.0')
        elif op == "STANDARDIZE":
            col = a["column"]
            lines.append(f'_mu, _sigma = {df}["{col}"].mean(), {df}["{col}"].std()')
            lines.append(f'{df}["{col}"] = ({df}["{col}"] - _mu) / _sigma if _sigma != 0 else 0.0')
        elif op == "ENCODE":
            col, method = a["column"], a["method"]
            if method == "ONEHOT":
                lines.append(f'{df} = pd.get_dummies({df}, columns=["{col}"])')
            else:
                lines.append(f'{df}["{col}"] = {df}["{col}"].astype("category").cat.codes')
        elif op == "RENAME":
            lines.append(f'{df} = {df}.rename(columns={{"{a["old"]}": "{a["new"]}"}})')
        elif op == "FILTER":
            expr_parts = []
            for cond in a["conditions"]:
                joiner, col, cop, val = cond
                pyop = {"==": "==", "!=": "!=", ">": ">", "<": "<", ">=": ">=", "<=": "<="}[cop]
                val_repr = repr(val)
                part = f'({df}["{col}"] {pyop} {val_repr})'
                if joiner:
                    part = (" & " if joiner == "AND" else " | ") + part
                expr_parts.append(part)
            expr = "".join(expr_parts)
            lines.append(f"{df} = {df}[{expr}]")
        elif op == "DEDUPLICATE":
            lines.append(f"{df} = {df}.drop_duplicates()")
        elif op == "CLIP":
            lines.append(f'{df}["{a["column"]}"] = {df}["{a["column"]}"].clip(lower={a["min"]}, upper={a["max"]})')
        elif op == "CAST_TYPE":
            pytype = {"INT": "int", "FLOAT": "float", "STRINGTYPE": "str"}[a["dtype"]]
            lines.append(f'{df}["{a["column"]}"] = {df}["{a["column"]}"].astype({pytype})')
        elif op == "TEXT_CASE":
            col, mode = a["column"], a["mode"]
            if mode == "LOWERCASE":
                lines.append(f'{df}["{col}"] = {df}["{col}"].astype(str).str.lower()')
            elif mode == "UPPERCASE":
                lines.append(f'{df}["{col}"] = {df}["{col}"].astype(str).str.upper()')
            else:
                lines.append(f'{df}["{col}"] = {df}["{col}"].astype(str).str.strip()')
        elif op == "SORT_BY":
            asc = a["direction"] == "ASC"
            lines.append(f'{df} = {df}.sort_values(by="{a["column"]}", ascending={asc})')
        elif op == "EXPORT":
            lines.append(f'{df}.to_csv("{a["path"]}", index=False)')
            lines.append(f'print("Exported", len({df}), "rows to {a["path"]}")')
        lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------
# 2. Direct execution against real pandas DataFrames (for live preview)
# ---------------------------------------------------------------------

def execute(ir, source_df):
    """
    source_df: the pandas.DataFrame loaded from the user's uploaded CSV.
    Every LOAD instruction in the IR is bound to this same dataframe
    (single-file pipelines, which is what the web UI supports).

    Returns: (dataframes: dict[str, DataFrame], trace: list[dict], export_path)
    """
    dataframes = {}
    trace = []
    export_path = None

    def snap(instr, df):
        trace.append({
            "line": instr.line,
            "op": instr.op,
            "df": instr.df,
            "rows": int(len(df)),
            "cols": int(len(df.columns)),
            "columns": list(map(str, df.columns)),
        })

    for instr in ir:
        df_name, a = instr.df, instr.args
        op = instr.op
        try:
            if op == "LOAD":
                dataframes[df_name] = source_df.copy()
                snap(instr, dataframes[df_name])
                continue

            df = dataframes[df_name]

            if op == "DROP_COLUMNS":
                df = df.drop(columns=a["columns"], errors="ignore")
            elif op == "FILLNA":
                col, strat = a["column"], a["strategy"]
                if col not in df.columns:
                    raise RuntimeExecError(f"column '{col}' does not exist in '{df_name}'", instr.line)
                if strat == "MEAN":
                    df[col] = df[col].fillna(df[col].mean())
                elif strat == "MEDIAN":
                    df[col] = df[col].fillna(df[col].median())
                elif strat == "MODE":
                    mode_vals = df[col].mode()
                    df[col] = df[col].fillna(mode_vals.iloc[0] if not mode_vals.empty else "")
                elif strat == "ZERO":
                    df[col] = df[col].fillna(0)
                else:
                    df[col] = df[col].fillna(strat)
            elif op == "NORMALIZE":
                col = a["column"]
                lo, hi = df[col].min(), df[col].max()
                df[col] = 0.0 if hi == lo else (df[col] - lo) / (hi - lo)
            elif op == "STANDARDIZE":
                col = a["column"]
                mu, sigma = df[col].mean(), df[col].std()
                df[col] = 0.0 if not sigma else (df[col] - mu) / sigma
            elif op == "ENCODE":
                col, method = a["column"], a["method"]
                if method == "ONEHOT":
                    df = pd.get_dummies(df, columns=[col])
                else:
                    df[col] = df[col].astype("category").cat.codes
            elif op == "RENAME":
                df = df.rename(columns={a["old"]: a["new"]})
            elif op == "FILTER":
                mask = None
                for joiner, col, cop, val in a["conditions"]:
                    if col not in df.columns:
                        raise RuntimeExecError(f"column '{col}' does not exist in '{df_name}'", instr.line)
                    series = df[col]
                    if cop == "==":
                        cur = series == val
                    elif cop == "!=":
                        cur = series != val
                    elif cop == ">":
                        cur = series > val
                    elif cop == "<":
                        cur = series < val
                    elif cop == ">=":
                        cur = series >= val
                    else:
                        cur = series <= val
                    if mask is None:
                        mask = cur
                    elif joiner == "AND":
                        mask = mask & cur
                    else:
                        mask = mask | cur
                df = df[mask]
            elif op == "DEDUPLICATE":
                df = df.drop_duplicates()
            elif op == "CLIP":
                df[a["column"]] = df[a["column"]].clip(lower=a["min"], upper=a["max"])
            elif op == "CAST_TYPE":
                pytype = {"INT": "int64", "FLOAT": "float64", "STRINGTYPE": "str"}[a["dtype"]]
                df[a["column"]] = df[a["column"]].astype(pytype)
            elif op == "TEXT_CASE":
                col, mode = a["column"], a["mode"]
                if mode == "LOWERCASE":
                    df[col] = df[col].astype(str).str.lower()
                elif mode == "UPPERCASE":
                    df[col] = df[col].astype(str).str.upper()
                else:
                    df[col] = df[col].astype(str).str.strip()
            elif op == "SORT_BY":
                df = df.sort_values(by=a["column"], ascending=(a["direction"] == "ASC"))
            elif op == "EXPORT":
                export_path = (df_name, a["path"])

            dataframes[df_name] = df
            snap(instr, df)
        except KeyError as e:
            raise RuntimeExecError(f"unknown column {e}", instr.line)

    return dataframes, trace, export_path
